#:kivy 2.2.0

ScreenManagement:
    HomeScreen:
    CameraScreen:
    WarnClothes:
    ConfirmNewClothes:
    ResultScreen:
    RecommendScreen:
    RecommendResultScreen:

<HomeScreen>:
    name: "home"
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 20

        Label:
            text: "Home Page"
            font_size: "24sp"

        Button:
            text: "Go to Camera"
            size_hint_y: None
            height: 50
            on_press: app.root.current = "camera"

        Button:
            text: "Exit"
            size_hint_y: None
            height: 50
            on_press: app.stop()

        Button:
            text: "Reccomend"
            size_hint_y: None
            height: 50
            on_press: app.root.current = "reccomend"

<CameraScreen>:
    name: "camera"
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 20

        Camera:
            id: camera_view
            index: 0
            resolution: (640, 480)
            play: False

        Label:
            text: "Camera Page"
            font_size: "24sp"

        Button:
            text: "Capture"
            size_hint_y: None
            height: 50
            on_press: root.capture()

        Button:
            text: "Show Results"
            size_hint_y: None
            height: 50
            on_press: app.root.current = "result"

        Button:
            text: "Back to Home"
            size_hint_y: None
            height: 50
            on_press: app.root.current = "home"

<WarnClothes>:
    name: "warn"
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 20

        Label:
            id: clothesDetail
            text: "You already has that clothes"
            font_size: "24sp"

        Button:
            text: "Capture Again"
            size_hint_y: None
            height: 50
            on_press: app.root.current = "camera"
        Button:
            text: "Back to Home"
            size_hint_y: None
            height: 50
            on_press: app.root.current = "home"



<ConfirmNewClothes>:
    name: "confirm"
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 20

        Label:
            id: clothesDetail
            text: "Loading text..."
            font_size: "24sp"

        Button:
            text: "Save Clothes"
            size_hint_y: None
            height: 50
            on_press: root.saveImage()

        Button:
            text: "Capture Again"
            size_hint_y: None
            height: 50
            on_press: app.root.current = "camera"
        Button:
            text: "Back to Home"
            size_hint_y: None
            height: 50
            on_press: app.root.current = "home"


<ResultScreen>:
    name: "result"
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 20

        Label:
            text: "Result Page"
            font_size: "24sp"

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True

            GridLayout:
                id: image_grid
                cols: 2
                spacing: 10
                padding: 10
                size_hint_y: None
                height: self.minimum_height
                row_default_height: '200dp'

        Button:
            text: "Back to Camera"
            size_hint_y: None
            height: 50
            on_press: app.root.current = "camera"

        Button:
            text: "Back to Home"
            size_hint_y: None
            height: 50
            on_press: app.root.current = "home"

<RecommendScreen>:
    name: "reccomend"
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 20

        Label:
            text: "Pick Your Outfit"
            font_size: 28

        Spinner:
            id: spinner
            text: "Select Type"
            values: []
            size_hint: (1, None)
            height: "40dp"
            on_text: root.on_selected(self.text)

        Button:
            text: "Next"
            size_hint_y: None
            height: dp(50)
            on_press: root.go_next()

<RecommendResultScreen>:
    name: "result_recommend"
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 20

        Label:
            text: "Best Reccomendation:"
            font_size: 28

        Label:
            id: recommend_label
            text: "Loading"
            font_size: 28

        Button:
            text: "Home"
            size_hint_y: None
            height: dp(50)
            on_press: app.root.current = "home"
